trigger:
- develop

variables:
  environmentName: 'instance'
  vmImageName: 'Ubuntu 20.04'

stages:

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:

    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      
- stage: Test
  jobs:
  - deployment: test
    displayName: Test
    pool:
       vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: sudo ansible all -m ping 



        


