trigger:
- develop

pool:
  name: Azure Pipelines

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
  displayName: 'Terraform : gcp'
  inputs:
    provider: gcp
    workingDirectory: terraform
    backendServiceGCP: 'terraform-automation'
    backendGCPBucketName: 'linops-bucket'
    backendGCPPrefix: terraform/state/dev.tfstate/dev.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
  displayName: 'Terraform : gcp'
  inputs:
    provider: gcp
    command: plan
    workingDirectory: terraform
    environmentServiceNameGCP: 'terraform-automation'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
  displayName: 'Terraform : gcp'
  inputs:
    provider: gcp
    command: apply
    workingDirectory: terraform
    environmentServiceNameGCP: 'terraform-automation'

- task: CopyFiles@2
  displayName: 'Copy Files to: terraform'
  inputs:
    SourceFolder: terraform
    TargetFolder: terraform

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: terraform'
  inputs:
    PathtoPublish: terraform
    ArtifactName: terraform

