variables:
  - group: GCP

trigger:
  branches:
    include:
    - develop

pool:
  name: Default

stages:
  - stage: Validation
    displayName: Validation
    jobs:
    - job: terraform
      pool:
        name: Default
      displayName: Terraform
      steps:
      
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install Terraform latest'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'Terraform : gcp'
        inputs:
          provider: gcp
          workingDirectory: terraform
          backendServiceGCP: 'terraform-automation'
          backendGCPBucketName: 'linops-bucket'
          backendGCPPrefix: terraform/state/dev.tfstate

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'Terraform : gcp'
        inputs:
          provider: gcp
          command: validate
          workingDirectory: terraform

      - task: Bash@3
        displayName: 'Check Terraform version'
        inputs:
          targetType: filePath
          filePath: './tests/terraform/t_version.sh'

      - task: Bash@3
        displayName: 'Check Ansible version'
        inputs:
          targetType: filePath
          filePath: './tests/ansible/a_version.sh'   
  
  - stage: Dev
    displayName: Dev
    jobs:
    - job: terraform
      pool:
        name: Default
      displayName: Terraform
      steps:

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install Terraform latest'

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'Terraform : gcp'
        inputs:
          provider: gcp
          workingDirectory: terraform
          backendServiceGCP: 'terraform-automation'
          backendGCPBucketName: 'linops-bucket'
          backendGCPPrefix: terraform/state/dev.tfstate
          
      - script: |
          terraform workspace new dev
          terraform workspace select dev
        workingDirectory: terraform
        displayName: 'Command Line Script'
          
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: Plan
        inputs:
          provider: gcp
          command: plan
          workingDirectory: terraform
          environmentServiceNameGCP: $(provider_service_acc)

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: Apply
        inputs:
          provider: gcp
          command: apply
          workingDirectory: terraform
          environmentServiceNameGCP: $(provider_service_acc)

      - task: Bash@3
        displayName: 'Check Dev hosts'
        inputs:
          targetType: filePath
          filePath: ./tests/hosts/dev.sh




