trigger: 
- develop

pool:
#  name: 'Test'
  demands: 
  - Agent.OS -equals Hosted Windows 2019 with VS2019

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
  displayName: 'Terraform : gcp'
  inputs:
    provider: gcp
    workingDirectory: '$(System.DefaultWorkingDirectory)/LinOps/develop'
    backendServiceGCP: 'terraform-automation'
    backendGCPBucketName: 'linop-bucket-test'

- task: Rimodi.tfsec-task.custom-build-release-task.terraformstaticcodeanalyzer@1
  displayName: 'Echo 0.58.6'


